version: "3.8"

services:
  api:
    container_name: ${APP_NAME:-dive-api}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${ROUTER_PORT:-8080}:${ROUTER_PORT:-8080}
      - ${DELVE_PORT:-2345}:${DELVE_PORT:-2345}
    environment:
      - DEBUG=${DEBUG:-false}
    volumes:
      - type: bind
        source: ./
        target: /app

networks:
  default:
